### ISSUE TITLE
DATA_PATH = '../data/MSVA_single_4511.h5' 这个h5文件在哪里

### ISSUE THREAD

**Issue by llb2015211499** [xunan0812/MultiSentiNet#1]
您好，我想运行你的代码 但是看了代码后没发现你的h5文件，不知道哪里能下载到这个文件

**Comment by xunan0812** [comment]
h5文件保存的是将每张图像通过预训练的CNN预处理后得到的1000实体向量和365维场景向量，相关模型都是使用引文的。抱歉，很久很久以后才看到回答这个消息，：）
