### ISSUE TITLE
请问可以提供一下h5文件吗？

### ISSUE THREAD

**Issue by Link-Li** [xunan0812/MultiSentiNet#2]
您好，读了您的文章，感觉非常有借鉴意义，我想运行一下你的代码，但是没有h5文件，请问您可以提供一下您处理好的h5文件吗？这是我的邮箱：17863110963@163.com
非常感谢！

**Comment by xunan0812** [comment]
h5文件保存的是将每张图像通过预训练的CNN预处理后得到的1000实体向量和365维场景向量，相关模型都是使用引文的。抱歉，很久很久以后才看到回答这个消息，：）
